# Generated by Django 5.1.1 on 2024-09-20 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestStep1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_service_logo_exists', models.BooleanField(default=False)),
                ('captcha_exists', models.BooleanField(default=False)),
                ('agree_on_terms_exists', models.BooleanField(default=False)),
                ('amount_displayed', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestStep2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=30)),
                ('card_cvv2', models.CharField(max_length=3)),
                ('card_expiration_date', models.CharField(max_length=7)),
                ('card_password', models.CharField(max_length=30)),
                ('card_status', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TestStep3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestStep4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shown_result', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.teststep1')),
                ('step2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.teststep2')),
                ('step3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.teststep3')),
                ('step4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.teststep4')),
            ],
        ),
    ]
