# Generated by Django 5.1.1 on 2024-09-20 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='step1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapper.teststep1'),
        ),
        migrations.AlterField(
            model_name='test',
            name='step2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapper.teststep2'),
        ),
        migrations.AlterField(
            model_name='test',
            name='step3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapper.teststep3'),
        ),
        migrations.AlterField(
            model_name='test',
            name='step4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapper.teststep4'),
        ),
    ]
